const crypto = require('crypto');

const AMD = 'MART_APP_METRICS_DAILY';   // 363 cols — broad Intercom product coverage
const MFR = 'MART_FEATURE_REPORTING';   // lifecycle/Fin-specific pre-built metrics

// ─── Columns to include from MART_APP_METRICS_DAILY ──────────────────────────
const AMD_COLS = [
  // Inbox / Conversations
  'COUNT_INBOX_CONVERSATIONS',
  'COUNT_INBOX_CONVERSATIONS_INBOUND',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND',
  'COUNT_INBOX_CONVERSATIONS_LOGGED_IN_USER',
  'COUNT_INBOX_CONVERSATIONS_LOGGED_OUT_USER',
  'COUNT_INBOX_CONVERSATIONS_CLOSED',
  'COUNT_INBOX_CONVERSATIONS_CLOSED_INBOUND',
  'COUNT_INBOX_CONVERSATIONS_WITH_TEAMMATE_REPLY',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_WITH_TEAMMATE_REPLY',
  'COUNT_INBOX_CONVERSATIONS_WITH_TEAMMATE_OR_BOT_REPLY',
  'COUNT_INBOX_CONVERSATIONS_CREATED_VIA_API',
  'COUNT_INBOX_CONVERSATIONS_WITH_END_USER',
  'COUNT_END_USERS_WITH_INBOX_CONVERSATION',
  'COUNT_END_USERS_WITH_INBOUND_INBOX_CONVERSATION',
  'COUNT_END_USERS_WITH_OUTBOUND_INBOX_CONVERSATION',
  'COUNT_SIDE_CONVERSATIONS',
  // Channels — all content types
  'COUNT_INBOX_CONVERSATIONS_CHAT_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_EMAIL_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_MESSENGER_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_WHATSAPP_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_SMS_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INSTAGRAM_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_FACEBOOK_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_TWITTER_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_PHONE_CALL_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_PHONE_SWITCH_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_POST_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_PUSH_ONLY_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_ARTICLE_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_CUSTOM_BOT_CONTENT_TYPE',
  // Channels — inbound by type
  'COUNT_INBOX_CONVERSATIONS_INBOUND_CHAT_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_EMAIL_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_MESSENGER_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_WHATSAPP_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_SMS_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_INSTAGRAM_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_FACEBOOK_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_TWITTER_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_PHONE_CALL_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_POST_CONTENT_TYPE',
  // Channels — outbound by type
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_CHAT_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_EMAIL_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_MESSENGER_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_WHATSAPP_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_SMS_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_INSTAGRAM_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_FACEBOOK_CONTENT_TYPE',
  'COUNT_INBOX_CONVERSATIONS_OUTBOUND_PHONE_CALL_CONTENT_TYPE',
  // Phone initial channel
  'COUNT_INBOX_CONVERSATIONS_PHONE_CALL_INITIAL_CHANNEL',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_PHONE_CALL_INITIAL_CHANNEL',
  'COUNT_INBOX_CONVERSATIONS_PHONE_SWITCH_INITIAL_CHANNEL',
  'COUNT_INBOX_CONVERSATIONS_PHONE_INTEGRATION_INITIAL_CHANNEL',
  // Fin AI
  'COUNT_INBOX_CONVERSATIONS_FIN_ELIGIBLE',
  'COUNT_INBOX_CONVERSATIONS_FIN_ADDRESSABLE',
  'COUNT_INBOX_CONVERSATIONS_FIN_ADDRESSABLE_FIN_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_FIN_SENT_AI_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_FIN_SENT_CUSTOM_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_FIN_SENT_INLINE_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_FIN_SENT_RELEVANT_CONTENT',
  'COUNT_INBOX_CONVERSATIONS_FIN_SENT_AI_AGENT_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_WITH_FIN_GUIDANCE',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_AI_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_AI_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_CUSTOM_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_CUSTOM_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_INLINE_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_INLINE_ANSWER',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_RELEVANT_CONTENT',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_RELEVANT_CONTENT',
  'COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_AI_AGENT_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_AI_AGENT_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_RESOLVED_BY_FIN_OR_LEGACY_RESOLUTION_BOT',
  'COUNT_INBOX_CONVERSATIONS_WITH_RESOLUTION_BOT',
  'COUNT_INBOX_CONVERSATIONS_RESOLUTION_BOT_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_RESOLUTION_BOT_SENT_CONTENT',
  'COUNT_INBOX_CONVERSATIONS_DEFLECTED_BY_RESOLUTION_BOT',
  'COUNT_INBOX_CONVERSATIONS_RESOLVED_BY_RESOLUTION_BOT',
  'COUNT_INBOX_CONVERSATIONS_ROUTED_TO_TEAM_BY_RESOLUTION_BOT',
  'COUNT_FIN_AI_AGENT_WORKFLOW_SENDS',
  'COUNT_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_POSITIVE_FEEDBACK',
  'COUNT_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_NEGATIVE_FEEDBACK',
  'COUNT_END_USERS_INTERACTING_WITH_FIN_EVER',
  'COUNT_END_USERS_INTERACTING_WITH_FIN_AI_ANSWERS_EVER',
  // Fin setup / in-app navigation
  'COUNT_VISITS_FIN_SETUP',
  'COUNT_VISITS_FIN_CONTENT',
  'COUNT_VISITS_FIN_CONTENT_SUGGESTIONS',
  'COUNT_VISITS_CUSTOM_ANSWERS',
  'COUNT_VISITS_FIN_SETTINGS',
  'COUNT_VISITS_MANAGE_FIN_USAGE',
  'COUNT_VISITS_EDIT_CUSTOM_ANSWER',
  'COUNT_VISITS_RESOLUTION_BOT_SECTION',
  'COUNT_VISITS_RESOLUTION_BOT_BEHAVIOURS',
  'COUNT_TEAMMATES_VISITED_FIN_SETUP',
  'COUNT_TEAMMATES_VISITED_FIN_CONTENT',
  'COUNT_TEAMMATES_VISITED_FIN_SETTINGS',
  'COUNT_TEAMMATES_VISITED_MANAGE_FIN_USAGE',
  'COUNT_TEAMMATES_VISITED_CUSTOM_ANSWERS',
  'COUNT_TEAMMATES_VISITED_RESOLUTION_BOT_SECTION',
  // AI Insights query types
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_INFORMATIONAL',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_PERSONALIZED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_ACTIONS',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_COMPLEX',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_INFORMATIONAL_FIN_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_PERSONALIZED_FIN_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_ACTIONS_FIN_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_COMPLEX_FIN_INVOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_INFORMATIONAL_RESOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_PERSONALIZED_RESOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_ACTIONS_RESOLVED',
  'COUNT_INBOX_CONVERSATIONS_AI_INSIGHTS_QUERY_TYPE_COMPLEX_RESOLVED',
  // Fin Procedures (also in AMD)
  'COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES',
  'COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_RESOLUTION',
  'COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_ESCALATED',
  'COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_HANDOFF',
  'COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_INTERRUPTED',
  'COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES',
  'COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_RESOLUTION',
  'COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_ESCALATED',
  'COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_HANDOFF',
  'COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_INTERRUPTED',
  'COUNT_INBOX_CONVERSATIONS_WITH_ESCALATED_PROCEDURES',
  'COUNT_PROCEDURES_CONFIGURED',
  'COUNT_PROCEDURES_STARTED',
  'COUNT_PROCEDURES_FINISHED',
  // CSAT / Ratings
  'COUNT_INBOX_CONVERSATIONS_WITH_TEAMMATE_RATING',
  'COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_5_OUT_OF_5',
  'COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_SATISFIED',
  'COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_UNSATISFIED',
  'COUNT_INBOX_CONVERSATIONS_WITH_BOT_RATING',
  'COUNT_INBOX_CONVERSATIONS_BOT_RATED_SATISFIED',
  'COUNT_INBOX_CONVERSATIONS_BOT_RATED_UNSATISFIED',
  'COUNT_INBOX_CONVERSATIONS_WITH_FIN_RATING',
  'COUNT_INBOX_CONVERSATIONS_FIN_RATED_SATISFIED',
  'COUNT_INBOX_CONVERSATIONS_FIN_RATED_UNSATISFIED',
  'COUNT_INBOX_CONVERSATIONS_WITH_AI_CSAT',
  'COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_5_OUT_OF_5',
  'COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_SATISFIED',
  'COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_UNSATISFIED',
  // Workflows & Automation
  'COUNT_INBOX_CONVERSATIONS_WITH_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_WITH_COMPLETED_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_WITH_WORKFLOW',
  'COUNT_INBOX_CONVERSATIONS_INBOUND_WITH_COMPLETED_WORKFLOW',
  'COUNT_WORKFLOWS_IN_CONVERSATIONS',
  'COUNT_WORKFLOWS_IN_CONVERSATIONS_INBOUND_CUSTOM_BOT',
  'COUNT_WORKFLOW_TYPES_IN_CONVERSATIONS',
  'COUNT_WORKFLOW_TRIGGERS',
  'COUNT_CUSTOM_BOTS_INBOUND',
  'COUNT_CUSTOM_BOTS_OUTBOUND',
  'COUNT_CUSTOM_BOTS_BOT_ON_BUTTON',
  'COUNT_NEW_WORKFLOWS',
  'COUNT_DRAFT_WORKFLOWS',
  'COUNT_LIVE_WORKFLOWS',
  'COUNT_PAUSED_WORKFLOWS',
  'COUNT_FIRST_SET_LIVE_WORKFLOWS',
  'COUNT_NEW_FIN_TASKS',
  'COUNT_DRAFT_FIN_TASKS',
  'COUNT_LIVE_FIN_TASKS',
  'COUNT_PAUSED_FIN_TASKS',
  'COUNT_FIRST_SET_LIVE_FIN_TASKS',
  'COUNT_CONVERSATIONS_WITH_STARTED_FIN_TASKS',
  'COUNT_CONVERSATIONS_WITH_FINISHED_FIN_TASKS',
  // Copilot
  'COUNT_CONVERSATIONS_WITH_COPILOT_SEARCH_SUCCESS',
  // Articles / Help Center
  'COUNT_LIVE_ARTICLES_ENG',
  'COUNT_LIVE_ARTICLES_NON_ENG',
  'COUNT_ANSWERS_LIVE',
  'COUNT_ARTICLE_SEARCHES_HELP_CENTER',
  'COUNT_ARTICLE_SEARCHES_MESSENGER',
  'COUNT_ARTICLE_VIEWS_HELP_CENTER',
  'COUNT_ARTICLE_VIEWS_MESSENGER',
  'COUNT_ARTICLE_VIEWS_MESSENGER_HELP_CENTER',
  'COUNT_ARTICLE_VIEWS_MESSENGER_SUGGESTED_ARTICLE',
  'COUNT_ARTICLE_VIEWS_MESSENGER_CONVERSATION',
  'COUNT_USERS_VIEWED_ARTICLE_HELP_CENTER',
  'COUNT_USERS_VIEWED_ARTICLE_MESSENGER',
  'COUNT_USERS_VIEWED_ARTICLE_MESSENGER_HELP_CENTER',
  'COUNT_USERS_VIEWED_ARTICLE_MESSENGER_SUGGESTED_ARTICLE',
  'COUNT_USERS_SEARCHED_ARTICLE_HELP_CENTER',
  'COUNT_USERS_SEARCHED_ARTICLE_MESSENGER',
  'COUNT_ARTICLES_VIEWED_HELP_CENTER',
  'COUNT_ARTICLES_VIEWED_MESSENGER',
  'COUNT_VIEWS_UNANSWERED_QUESTIONS',
  'COUNT_VIEWS_UNANSWERED_QUESTION_DETAIL',
  'COUNT_CLICKS_SUGGESTED_ANSWER_ACTION',
  'COUNT_VIEWS_RESOLUTION_BOT_REPORT',
  'COUNT_TEAMMATES_VISITED_UNANSWERED_QUESTIONS',
  'COUNT_TEAMMATES_CLICKED_SUGGESTED_ANSWER_ACTION',
  'COUNT_TEAMMATES_VIEWED_RESOLUTION_BOT_REPORT',
  // Outbound & Engagement
  'COUNT_OUTBOUND_RECEIPTS',
  'COUNT_OUTBOUND_END_USERS_REACHED',
  'COUNT_OUTBOUND_END_USERS_REACHED_LOGGED_IN_USER',
  'COUNT_OUTBOUND_END_USERS_REACHED_LOGGED_OUT_USER',
  'COUNT_OUTBOUND_RECEIPTS_LOGGED_IN_USER',
  'COUNT_OUTBOUND_RECEIPTS_LOGGED_OUT_USER',
  'COUNT_OUTBOUND_RECEIPTS_EMAIL_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_POST_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_PUSH_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_CHAT_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_CUSTOM_BOT_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_BANNER_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_CAROUSEL_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_PRODUCT_TOUR_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_SURVEY_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_SMS_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_CONVERSATION_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_TOOLTIP_GROUP_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_ARTICLE_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_CHECKLIST_CONTENT_TYPE',
  'COUNT_OUTBOUND_RECEIPTS_SERIES',
  'COUNT_SERIES_SET_LIVE',
  'COUNT_OUTBOUNDS_SET_LIVE',
  'COUNT_OUTBOUNDS_SET_LIVE_CHAT_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_EMAIL_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_PUSH_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_SMS_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_CUSTOM_BOT_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_PRODUCT_TOUR_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_BANNER_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_SURVEY_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_CAROUSEL_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_CHECKLIST_CONTENT_TYPE',
  'COUNT_OUTBOUNDS_SET_LIVE_NEWS_ITEM_CONTENT_TYPE',
  // Phone / Calls
  'COUNT_PHONE_CALLS',
  'COUNT_PHONE_CALLS_INITIATED',
  'COUNT_PHONE_CALLS_ACCEPTED',
  'COUNT_PHONE_CALLS_ENDED',
  'COUNT_INBOUND_PHONE_CALLS_ACCEPTED',
  'COUNT_CALLS',
  'COUNT_CALLS_ANSWERED',
  'COUNT_CALLS_INBOUND',
  'COUNT_CALLS_OUTBOUND',
  'COUNT_CALLS_TYPE_MESSENGER',
  'COUNT_CALLS_TYPE_PHONE',
  'COUNT_CALLS_WITH_END_USER',
  'COUNT_CALLS_WITH_TEAMMATE',
  'TOTAL_CALL_DURATION_SECONDS',
  'COUNT_MESSENGER_CALLS_INITIATED',
  'COUNT_MESSENGER_CALLS_JOINED',
  'COUNT_MESSENGER_CALLS_ENDED',
  'COUNT_INBOX_CONVERSATIONS_WITH_CALL',
  'COUNT_INBOX_CONVERSATIONS_WITH_CALL_ANSWERED',
  'COUNT_INBOX_CONVERSATIONS_WITH_INBOUND_CALL',
  'COUNT_INBOX_CONVERSATIONS_WITH_OUTBOUND_CALL',
  'COUNT_INBOX_CONVERSATIONS_WITH_CALL_TYPE_MESSENGER',
  'COUNT_INBOX_CONVERSATIONS_WITH_CALL_TYPE_PHONE',
  'COUNT_PHONE_SETTING_VIEWS',
  'COUNT_TEAMMATES_VIEWED_PHONE_SETTINGS',
  // Tickets
  'COUNT_TICKETS',
  'COUNT_TICKETS_CREATED_BY_END_USER',
  'COUNT_TICKETS_CREATED_BY_TEAMMATE',
  'COUNT_TICKETS_CREATED_VIA_CHILD_TICKET',
  'COUNT_TICKETS_CREATED_VIA_CONVERTED_TO_TICKET',
  'COUNT_TICKETS_CREATED_VIA_CUSTOM_BOT',
  'COUNT_TICKETS_CREATED_VIA_STANDALONE_TICKET',
  'COUNT_TICKETS_CREATED_VIA_FORM_SENT_TO_USER',
  'COUNT_TICKETS_CREATED_VIA_USER_INITIATED',
  'COUNT_TICKETS_CREATED_VIA_API',
  'COUNT_TICKETS_CATEGORY_TASK',
  'COUNT_TICKETS_CATEGORY_REQUEST',
  'COUNT_TICKETS_CATEGORY_TRACKER',
  'COUNT_TICKETS_VISIBLE_TO_END_USER',
  // Teammates
  'COUNT_TEAMMATES_ACTIVE',
  'COUNT_TEAMMATES_REPLIED_TO_CONVERSATIONS',
  'COUNT_TEAMMATES_ASSIGNED_CONVERSATIONS',
  'COUNT_TEAMMATES_MANUAL_ASSIGNED_CONVERSATIONS',
  'COUNT_REPLIES_FROM_TEAMMATES',
  'COUNT_ADMINS_OPENED_INBOX',
  'COUNT_ADMINS_OPENED_DEFAULT_INBOX',
  'COUNT_ADMINS_OPENED_TEAM_INBOX',
  'COUNT_ADMINS_OPENED_ADMIN_INBOX',
  'COUNT_ADMINS_OPENED_INBOX_VIEW',
  'COUNT_TEAMMATES_VIEWING_REPORTS',
  'COUNT_TEAMMATES_MINUTES_WITH_EVENT',
  // Macros & Rules
  'COUNT_INBOX_CONVERSATIONS_MACRO_INSERTED',
  'COUNT_MACRO_INSERTIONS',
  'COUNT_UNIQUE_MACROS_INSERTED',
  'COUNT_TEAMMATES_INSERTED_MACROS',
  'COUNT_INBOX_CONVERSATIONS_WITH_ATTRIBUTE',
  'COUNT_INBOX_CONVERSATIONS_WITH_NON_DEFAULT_ATTRIBUTE',
  'COUNT_INBOX_CONVERSATIONS_WITH_SLA',
  'COUNT_INBOX_CONVERSATIONS_WITH_INBOX_RULE',
  'COUNT_INBOX_CONVERSATIONS_WITH_BALANCED_ASSIGNMENT',
  'COUNT_INBOX_CONVERSATIONS_WITH_ROUND_ROBIN_ASSIGNMENT',
  'COUNT_INBOX_CONVERSATIONS_WITH_TAG',
  'COUNT_INBOX_CONVERSATIONS_WITH_TAG_APPLIED_BY_WORKFLOW',
  'COUNT_CONVERSATION_PARTS_WITH_TAG',
  'COUNT_CONVERSATION_PARTS_WITH_TAG_APPLIED_BY_WORKFLOW',
  'COUNT_CONVERSATION_TOPIC_VERSIONS_CREATED',
  // Misc
  'COUNT_ACTIVE_INTEGRATIONS',
  'COUNT_OSA2_REPORTS_DELIVERED',
  'COUNT_CSV_REPORTS_DELIVERED',
  'COUNT_MESSENGER_SHARING_INITIATED',
];

// ─── Columns unique to MART_FEATURE_REPORTING ────────────────────────────────
const MFR_ONLY_COLS = [
  // CX Score
  'POSITIVE_CUSTOMER_EXPERIENCE_SCORES_RATE',
  'COUNT_CX_SCORE_DRILL_INS',
  'COUNT_CX_SCORE_DRILL_INS_AND_REPORT_VIEWS',
  // Service
  'COUNT_SERVICE_CONVERSATIONS',
  // Copilot (MFR-specific)
  'COUNT_SUGGESTIONS_GENERATED',
  'COUNT_ACCEPTED_SUGGESTIONS',
  // Topics
  'COUNT_TOPICS_GENERATED',
  'COUNT_TOPICS_EXPLORER_EVENTS',
  'COUNT_TOPIC_TRENDS_NAVIGATIONS',
  'COUNT_TOPIC_TRENDS_ACTIVE_WEEKS',
  // Sales Agent
  'COUNT_CONTACT_CAPTURES',
  'COUNT_ABANDONED_CONVERSATIONS',
  'COUNT_DISQUALIFIED_CONVERSATIONS',
  'COUNT_PRODUCT_DISCOVERY_CONVERSATIONS',
  'COUNT_UNCHARGEABLE_CONVERSATIONS',
  'COUNT_SALES_AGENT_CONVERSATIONS',
  'COUNT_SALES_AGENT_QUALIFIED_CONVERSATIONS',
  'COUNT_SALES_AGENT_CHARGEABLE_CONVERSATIONS',
  'SALES_AGENT_ABANDONMENT_RATE',
  'SALES_AGENT_CHARGEABLE_CONVERSATIONS_RATE',
  'SALES_AGENT_CONTACT_CAPTURE_RATE',
  // Fin AI agent TOTAL variants
  'TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS',
  'TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_POSITIVE_FEEDBACK',
  'TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_NEGATIVE_FEEDBACK',
  // Phone / Fin Voice (MFR has detailed Fin Voice metrics)
  'COUNT_FIN_VOICE_PLAYGROUND_SESSIONS',
  'COUNT_INBOUND_PHONE_CONVERSATIONS',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_FROM_FIN_VOICE_USERS',
  'INBOUND_PHONE_CONVERSATIONS_FROM_FIN_VOICE_USERS_INVOLVEMENT_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_ABANDONED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_ABANDONED_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_DEFLECTED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_DEFLECTED_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_ROUTED_TO_TEAMMATES',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_ROUTED_TO_TEAMMATES_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_INSTANTLY_ESCALATED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_INSTANTLY_ESCALATED_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_HARD_RESOLVED_CALLS',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_SOFT_RESOLVED_CALLS',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_RESOLVED_CALLS',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_RESOLUTION_RATE',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_HARD_RESOLUTION_RATE',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_SOFT_RESOLUTION_RATE',
  // Phone Fin — by query type
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_INFORMATIONAL_QUERY_TYPE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_INFORMATIONAL_QUERY_TYPE_RESOLVED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_INFORMATIONAL_QUERY_TYPE_RESOLUTION_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_PERSONALIZED_QUERY_TYPE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_PERSONALIZED_QUERY_TYPE_RESOLVED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_PERSONALIZED_QUERY_TYPE_RESOLUTION_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_ACTIONS_QUERY_TYPE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_ACTIONS_QUERY_TYPE_RESOLVED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_ACTIONS_QUERY_TYPE_RESOLUTION_RATE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_COMPLEX_QUERY_TYPE',
  'COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_COMPLEX_QUERY_TYPE_RESOLVED',
  'INBOUND_PHONE_CONVERSATIONS_WITH_FIN_COMPLEX_QUERY_TYPE_RESOLUTION_RATE',
];

// ─── Manual label overrides ───────────────────────────────────────────────────
// Only needed where the auto-generated label would be confusing or missing context.
const LABEL_OVERRIDES = {
  // CX Score
  POSITIVE_CUSTOMER_EXPERIENCE_SCORES_RATE:                           'CX Score — positive rate',
  COUNT_CX_SCORE_DRILL_INS:                                           'CX Score — drill-ins',
  COUNT_CX_SCORE_DRILL_INS_AND_REPORT_VIEWS:                          'CX Score — drill-ins & report views',
  // Core inbox
  COUNT_INBOX_CONVERSATIONS:                                          'Inbox conversations (total)',
  COUNT_INBOX_CONVERSATIONS_INBOUND:                                  'Inbound conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND:                                 'Outbound conversations (inbox)',
  COUNT_INBOX_CONVERSATIONS_CLOSED:                                   'Conversations closed',
  COUNT_INBOX_CONVERSATIONS_CLOSED_INBOUND:                           'Inbound conversations closed',
  COUNT_INBOX_CONVERSATIONS_WITH_END_USER:                            'Conversations with end user',
  // Channels
  COUNT_INBOX_CONVERSATIONS_CHAT_CONTENT_TYPE:                        'Chat conversations',
  COUNT_INBOX_CONVERSATIONS_EMAIL_CONTENT_TYPE:                       'Email conversations',
  COUNT_INBOX_CONVERSATIONS_MESSENGER_CONTENT_TYPE:                   'Messenger conversations',
  COUNT_INBOX_CONVERSATIONS_WHATSAPP_CONTENT_TYPE:                    'WhatsApp conversations',
  COUNT_INBOX_CONVERSATIONS_SMS_CONTENT_TYPE:                         'SMS conversations',
  COUNT_INBOX_CONVERSATIONS_INSTAGRAM_CONTENT_TYPE:                   'Instagram conversations',
  COUNT_INBOX_CONVERSATIONS_FACEBOOK_CONTENT_TYPE:                    'Facebook conversations',
  COUNT_INBOX_CONVERSATIONS_TWITTER_CONTENT_TYPE:                     'Twitter/X conversations',
  COUNT_INBOX_CONVERSATIONS_PHONE_CALL_CONTENT_TYPE:                  'Phone call conversations',
  COUNT_INBOX_CONVERSATIONS_POST_CONTENT_TYPE:                        'Post conversations',
  COUNT_INBOX_CONVERSATIONS_PUSH_ONLY_CONTENT_TYPE:                   'Push-only conversations',
  COUNT_INBOX_CONVERSATIONS_ARTICLE_CONTENT_TYPE:                     'Article conversations',
  COUNT_INBOX_CONVERSATIONS_CUSTOM_BOT_CONTENT_TYPE:                  'Custom bot conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_CHAT_CONTENT_TYPE:                'Inbound chat conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_EMAIL_CONTENT_TYPE:               'Inbound email conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_MESSENGER_CONTENT_TYPE:           'Inbound Messenger conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_WHATSAPP_CONTENT_TYPE:            'Inbound WhatsApp conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_SMS_CONTENT_TYPE:                 'Inbound SMS conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_INSTAGRAM_CONTENT_TYPE:           'Inbound Instagram conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_FACEBOOK_CONTENT_TYPE:            'Inbound Facebook conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_TWITTER_CONTENT_TYPE:             'Inbound Twitter/X conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_PHONE_CALL_CONTENT_TYPE:          'Inbound phone call conversations',
  COUNT_INBOX_CONVERSATIONS_INBOUND_POST_CONTENT_TYPE:                'Inbound post conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_CHAT_CONTENT_TYPE:               'Outbound chat conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_EMAIL_CONTENT_TYPE:              'Outbound email conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_MESSENGER_CONTENT_TYPE:          'Outbound Messenger conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_WHATSAPP_CONTENT_TYPE:           'Outbound WhatsApp conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_SMS_CONTENT_TYPE:                'Outbound SMS conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_INSTAGRAM_CONTENT_TYPE:          'Outbound Instagram conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_FACEBOOK_CONTENT_TYPE:           'Outbound Facebook conversations',
  COUNT_INBOX_CONVERSATIONS_OUTBOUND_PHONE_CALL_CONTENT_TYPE:         'Outbound phone call conversations',
  // Fin AI
  COUNT_INBOX_CONVERSATIONS_FIN_ELIGIBLE:                             'Fin eligible conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_ADDRESSABLE:                          'Fin addressable conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_ADDRESSABLE_FIN_INVOLVED:             'Fin addressable — Fin involved',
  COUNT_INBOX_CONVERSATIONS_FIN_SENT_AI_ANSWER:                       'Fin AI answer conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_SENT_CUSTOM_ANSWER:                   'Fin custom answer conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_SENT_INLINE_ANSWER:                   'Fin inline answer conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_SENT_RELEVANT_CONTENT:                'Fin relevant content conversations',
  COUNT_INBOX_CONVERSATIONS_FIN_SENT_AI_AGENT_WORKFLOW:               'Fin AI agent workflow conversations',
  COUNT_INBOX_CONVERSATIONS_WITH_FIN_GUIDANCE:                        'Fin guidance — conversations using guidance',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED:                            'Fin hard resolved conversations',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED:                            'Fin soft resolved conversations',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_AI_ANSWER:           'Hard resolved by Fin AI answer',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_AI_ANSWER:           'Soft resolved by Fin AI answer',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_CUSTOM_ANSWER:       'Hard resolved by Fin custom answer',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_CUSTOM_ANSWER:       'Soft resolved by Fin custom answer',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_INLINE_ANSWER:       'Hard resolved by Fin inline answer',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_INLINE_ANSWER:       'Soft resolved by Fin inline answer',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_RELEVANT_CONTENT:    'Hard resolved by Fin relevant content',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_RELEVANT_CONTENT:    'Soft resolved by Fin relevant content',
  COUNT_INBOX_CONVERSATIONS_HARD_RESOLVED_BY_FIN_AI_AGENT_WORKFLOW:   'Hard resolved by Fin AI agent workflow',
  COUNT_INBOX_CONVERSATIONS_SOFT_RESOLVED_BY_FIN_AI_AGENT_WORKFLOW:   'Soft resolved by Fin AI agent workflow',
  COUNT_INBOX_CONVERSATIONS_RESOLVED_BY_FIN_OR_LEGACY_RESOLUTION_BOT: 'Resolved by Fin or resolution bot',
  COUNT_INBOX_CONVERSATIONS_WITH_RESOLUTION_BOT:                      'Conversations with resolution bot',
  COUNT_INBOX_CONVERSATIONS_RESOLUTION_BOT_INVOLVED:                  'Conversations — resolution bot involved',
  COUNT_INBOX_CONVERSATIONS_DEFLECTED_BY_RESOLUTION_BOT:              'Conversations deflected by resolution bot',
  COUNT_INBOX_CONVERSATIONS_RESOLVED_BY_RESOLUTION_BOT:               'Conversations resolved by resolution bot',
  COUNT_INBOX_CONVERSATIONS_ROUTED_TO_TEAM_BY_RESOLUTION_BOT:         'Conversations routed to team by resolution bot',
  COUNT_FIN_AI_AGENT_WORKFLOW_SENDS:                                  'Fin AI agent workflow sends',
  COUNT_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_POSITIVE_FEEDBACK:            'Fin AI agent workflow — positive feedback',
  COUNT_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_NEGATIVE_FEEDBACK:            'Fin AI agent workflow — negative feedback',
  TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS:                                  'Fin AI agent workflow sends (total)',
  TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_POSITIVE_FEEDBACK:            'Fin AI agent workflow — positive feedback (total)',
  TOTAL_FIN_AI_AGENT_WORKFLOW_SENDS_GOT_NEGATIVE_FEEDBACK:            'Fin AI agent workflow — negative feedback (total)',
  COUNT_END_USERS_INTERACTING_WITH_FIN_EVER:                          'End users who interacted with Fin',
  COUNT_END_USERS_INTERACTING_WITH_FIN_AI_ANSWERS_EVER:               'End users who received Fin AI answers',
  // Fin procedures
  COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES:                   'Fin procedures used',
  COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_RESOLUTION:        'Fin procedures — resolved',
  COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_ESCALATED:         'Fin procedures — escalated',
  COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_HANDOFF:           'Fin procedures — handoff',
  COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_INTERRUPTED:       'Fin procedures — interrupted',
  COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES:       'Fin procedures (addressable)',
  COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_RESOLUTION:  'Fin procedures (addressable) — resolved',
  COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_ESCALATED:   'Fin procedures (addressable) — escalated',
  COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_HANDOFF:     'Fin procedures (addressable) — handoff',
  COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_INTERRUPTED: 'Fin procedures (addressable) — interrupted',
  COUNT_INBOX_CONVERSATIONS_WITH_ESCALATED_PROCEDURES:                'Conversations with escalated procedures',
  // CSAT
  COUNT_INBOX_CONVERSATIONS_WITH_TEAMMATE_RATING:                     'CSAT ratings (human)',
  COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_5_OUT_OF_5:                'CSAT — human 5/5',
  COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_SATISFIED:                 'CSAT — human satisfied',
  COUNT_INBOX_CONVERSATIONS_TEAMMATE_RATED_UNSATISFIED:               'CSAT — human unsatisfied',
  COUNT_INBOX_CONVERSATIONS_WITH_BOT_RATING:                          'CSAT ratings (bot)',
  COUNT_INBOX_CONVERSATIONS_BOT_RATED_SATISFIED:                      'CSAT — bot satisfied',
  COUNT_INBOX_CONVERSATIONS_BOT_RATED_UNSATISFIED:                    'CSAT — bot unsatisfied',
  COUNT_INBOX_CONVERSATIONS_WITH_FIN_RATING:                          'CSAT ratings (Fin)',
  COUNT_INBOX_CONVERSATIONS_FIN_RATED_SATISFIED:                      'CSAT — Fin satisfied',
  COUNT_INBOX_CONVERSATIONS_FIN_RATED_UNSATISFIED:                    'CSAT — Fin unsatisfied',
  COUNT_INBOX_CONVERSATIONS_WITH_AI_CSAT:                             'AI CSAT ratings',
  COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_5_OUT_OF_5:                 'AI CSAT — 5/5',
  COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_SATISFIED:                  'AI CSAT — satisfied',
  COUNT_INBOX_CONVERSATIONS_AI_CSAT_RATED_UNSATISFIED:                'AI CSAT — unsatisfied',
  // Workflows
  COUNT_INBOX_CONVERSATIONS_WITH_WORKFLOW:                            'Conversations with workflow',
  COUNT_INBOX_CONVERSATIONS_WITH_COMPLETED_WORKFLOW:                  'Conversations with completed workflow',
  COUNT_INBOX_CONVERSATIONS_INBOUND_WITH_WORKFLOW:                    'Inbound conversations with workflow',
  COUNT_INBOX_CONVERSATIONS_INBOUND_WITH_COMPLETED_WORKFLOW:          'Inbound conversations with completed workflow',
  // Copilot
  COUNT_SUGGESTIONS_GENERATED:                                        'Copilot suggestions generated',
  COUNT_ACCEPTED_SUGGESTIONS:                                         'Copilot suggestions accepted',
  COUNT_CONVERSATIONS_WITH_COPILOT_SEARCH_SUCCESS:                    'Conversations with Copilot search',
  // Articles
  COUNT_LIVE_ARTICLES_ENG:                                            'Live articles (English)',
  COUNT_LIVE_ARTICLES_NON_ENG:                                        'Live articles (non-English)',
  COUNT_ARTICLE_VIEWS_HELP_CENTER:                                    'Article views — Help Center',
  COUNT_ARTICLE_VIEWS_MESSENGER:                                      'Article views — Messenger',
  COUNT_ARTICLE_VIEWS_MESSENGER_HELP_CENTER:                          'Article views — Messenger Help Center',
  COUNT_ARTICLE_VIEWS_MESSENGER_SUGGESTED_ARTICLE:                    'Article views — Messenger suggested',
  COUNT_ARTICLE_VIEWS_MESSENGER_CONVERSATION:                         'Article views — Messenger conversation',
  COUNT_ARTICLE_SEARCHES_HELP_CENTER:                                 'Article searches — Help Center',
  COUNT_ARTICLE_SEARCHES_MESSENGER:                                   'Article searches — Messenger',
  COUNT_USERS_VIEWED_ARTICLE_HELP_CENTER:                             'Users viewed articles — Help Center',
  COUNT_USERS_VIEWED_ARTICLE_MESSENGER:                               'Users viewed articles — Messenger',
  COUNT_USERS_SEARCHED_ARTICLE_HELP_CENTER:                           'Users searched articles — Help Center',
  COUNT_USERS_SEARCHED_ARTICLE_MESSENGER:                             'Users searched articles — Messenger',
  // Outbound
  COUNT_OUTBOUND_RECEIPTS:                                            'Outbound receipts (total)',
  COUNT_OUTBOUND_END_USERS_REACHED:                                   'Outbound — end users reached',
  COUNT_OUTBOUND_RECEIPTS_EMAIL_CONTENT_TYPE:                         'Outbound receipts — Email',
  COUNT_OUTBOUND_RECEIPTS_PUSH_CONTENT_TYPE:                          'Outbound receipts — Push',
  COUNT_OUTBOUND_RECEIPTS_CHAT_CONTENT_TYPE:                          'Outbound receipts — Chat',
  COUNT_OUTBOUND_RECEIPTS_CUSTOM_BOT_CONTENT_TYPE:                    'Outbound receipts — Custom bot',
  COUNT_OUTBOUND_RECEIPTS_BANNER_CONTENT_TYPE:                        'Outbound receipts — Banner',
  COUNT_OUTBOUND_RECEIPTS_CAROUSEL_CONTENT_TYPE:                      'Outbound receipts — Carousel',
  COUNT_OUTBOUND_RECEIPTS_PRODUCT_TOUR_CONTENT_TYPE:                  'Outbound receipts — Product Tour',
  COUNT_OUTBOUND_RECEIPTS_SURVEY_CONTENT_TYPE:                        'Outbound receipts — Survey',
  COUNT_OUTBOUND_RECEIPTS_SMS_CONTENT_TYPE:                           'Outbound receipts — SMS',
  COUNT_OUTBOUND_RECEIPTS_SERIES:                                     'Outbound receipts — Series',
  COUNT_OUTBOUND_RECEIPTS_CHECKLIST_CONTENT_TYPE:                     'Outbound receipts — Checklist',
  COUNT_OUTBOUND_RECEIPTS_TOOLTIP_GROUP_CONTENT_TYPE:                 'Outbound receipts — Tooltip',
  COUNT_OUTBOUND_RECEIPTS_ARTICLE_CONTENT_TYPE:                       'Outbound receipts — Article',
  COUNT_OUTBOUND_RECEIPTS_POST_CONTENT_TYPE:                          'Outbound receipts — Post',
  COUNT_OUTBOUND_RECEIPTS_CONVERSATION_CONTENT_TYPE:                  'Outbound receipts — Conversation',
  COUNT_OUTBOUNDS_SET_LIVE:                                           'Outbounds set live (total)',
  COUNT_SERIES_SET_LIVE:                                              'Series set live',
  // Phone
  COUNT_PHONE_CALLS:                                                  'Phone calls (total)',
  COUNT_INBOUND_PHONE_CALLS_ACCEPTED:                                 'Inbound phone calls accepted',
  TOTAL_CALL_DURATION_SECONDS:                                        'Call duration (seconds)',
  COUNT_INBOUND_PHONE_CONVERSATIONS:                                  'Phone conversations (inbound)',
  COUNT_INBOUND_PHONE_CONVERSATIONS_FROM_FIN_VOICE_USERS:             'Phone convos from Fin Voice users',
  INBOUND_PHONE_CONVERSATIONS_FROM_FIN_VOICE_USERS_INVOLVEMENT_RATE:  'Fin Voice user involvement rate',
  COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS:                   'Phone — Fin handled calls',
  COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_HARD_RESOLVED_CALLS:     'Phone — Fin hard resolved',
  COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_SOFT_RESOLVED_CALLS:     'Phone — Fin soft resolved',
  COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_RESOLVED_CALLS:          'Phone — Fin resolved',
  COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_DEFLECTED:         'Phone — Fin deflected',
  INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_DEFLECTED_RATE:          'Phone — Fin deflection rate',
  INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_RESOLUTION_RATE:         'Phone — Fin resolution rate',
  INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_HARD_RESOLUTION_RATE:    'Phone — Fin hard resolution rate',
  INBOUND_PHONE_CONVERSATIONS_WITH_FIN_CALLS_SOFT_RESOLUTION_RATE:    'Phone — Fin soft resolution rate',
  // Sales Agent
  COUNT_SALES_AGENT_CONVERSATIONS:                                    'Sales agent conversations',
  COUNT_SALES_AGENT_QUALIFIED_CONVERSATIONS:                          'Sales agent qualified conversations',
  COUNT_SALES_AGENT_CHARGEABLE_CONVERSATIONS:                         'Sales agent chargeable conversations',
  COUNT_CONTACT_CAPTURES:                                             'Sales agent — contact captures',
  COUNT_ABANDONED_CONVERSATIONS:                                      'Sales agent — abandoned conversations',
  COUNT_DISQUALIFIED_CONVERSATIONS:                                   'Sales agent — disqualified conversations',
  COUNT_PRODUCT_DISCOVERY_CONVERSATIONS:                              'Sales agent — product discovery conversations',
  COUNT_UNCHARGEABLE_CONVERSATIONS:                                   'Sales agent — unchargeable conversations',
  SALES_AGENT_ABANDONMENT_RATE:                                       'Sales agent — abandonment rate',
  SALES_AGENT_CHARGEABLE_CONVERSATIONS_RATE:                          'Sales agent — chargeable rate',
  SALES_AGENT_CONTACT_CAPTURE_RATE:                                   'Sales agent — contact capture rate',
  // Topics
  COUNT_TOPICS_GENERATED:                                             'Topics generated',
  COUNT_TOPICS_EXPLORER_EVENTS:                                       'Topics explorer events',
  COUNT_TOPIC_TRENDS_NAVIGATIONS:                                     'Topic trends navigations',
  COUNT_TOPIC_TRENDS_ACTIVE_WEEKS:                                    'Topic trends active weeks',
  // Teammates
  COUNT_TEAMMATES_ACTIVE:                                             'Active teammates',
  COUNT_TEAMMATES_REPLIED_TO_CONVERSATIONS:                           'Teammates replied to conversations',
  COUNT_ADMINS_OPENED_INBOX:                                          'Teammates opened inbox',
  // Tickets
  COUNT_TICKETS:                                                      'Tickets (total)',
  // Fin Setup & Configuration
  COUNT_PROCEDURES_CONFIGURED:                                         'Fin procedures — configured',
  COUNT_PROCEDURES_STARTED:                                            'Fin procedures — started',
  COUNT_PROCEDURES_FINISHED:                                           'Fin procedures — finished',
  COUNT_LIVE_FIN_TASKS:                                                'Fin tasks — live (total)',
  COUNT_FIRST_SET_LIVE_FIN_TASKS:                                      'Fin tasks — first set live',
  COUNT_NEW_FIN_TASKS:                                                 'Fin tasks — new',
  COUNT_DRAFT_FIN_TASKS:                                               'Fin tasks — in draft',
  COUNT_PAUSED_FIN_TASKS:                                              'Fin tasks — paused',
  COUNT_ANSWERS_LIVE:                                                  'Fin custom answers — live',
  COUNT_INBOX_CONVERSATIONS_WITH_ATTRIBUTE:                            'Conversation attributes — used',
  COUNT_INBOX_CONVERSATIONS_WITH_NON_DEFAULT_ATTRIBUTE:                'Conversation attributes — custom',
  COUNT_VISITS_FIN_SETUP:                                              'Fin setup — page visits',
  COUNT_VISITS_FIN_CONTENT:                                            'Fin content — page visits',
  COUNT_VISITS_FIN_SETTINGS:                                           'Fin settings — page visits',
  COUNT_VISITS_FIN_CONTENT_SUGGESTIONS:                                'Fin content suggestions — visits',
  COUNT_VISITS_CUSTOM_ANSWERS:                                         'Custom answers — page visits',
  COUNT_TEAMMATES_VISITED_FIN_SETUP:                                   'Fin setup — teammates visited',
  COUNT_TEAMMATES_VISITED_FIN_CONTENT:                                 'Fin content — teammates visited',
  COUNT_TEAMMATES_VISITED_FIN_SETTINGS:                                'Fin settings — teammates visited',
  COUNT_TEAMMATES_VISITED_CUSTOM_ANSWERS:                              'Custom answers — teammates visited',
};

// ─── Auto-label fallback ──────────────────────────────────────────────────────
// Converts a Snowflake column name into a readable label for anything not in LABEL_OVERRIDES.
function autoLabel(col) {
  let s = col
    .replace(/^COUNT_INBOX_CONVERSATIONS_INBOUND_/, 'Inbound convos — ')
    .replace(/^COUNT_INBOX_CONVERSATIONS_OUTBOUND_/, 'Outbound convos — ')
    .replace(/^COUNT_INBOX_CONVERSATIONS_/, 'Convos — ')
    .replace(/^COUNT_INBOUND_PHONE_CONVERSATIONS_WITH_FIN_/, 'Phone (Fin) — ')
    .replace(/^COUNT_INBOUND_PHONE_CONVERSATIONS_/, 'Phone convos — ')
    .replace(/^INBOUND_PHONE_CONVERSATIONS_WITH_FIN_/, 'Phone (Fin) rate — ')
    .replace(/^INBOUND_PHONE_CONVERSATIONS_/, 'Phone convos rate — ')
    .replace(/^COUNT_OUTBOUND_RECEIPTS_/, 'Outbound receipts — ')
    .replace(/^COUNT_OUTBOUNDS_SET_LIVE_/, 'Outbounds live — ')
    .replace(/^COUNT_TEAMMATES_VISITED_/, 'Teammates visited — ')
    .replace(/^COUNT_TEAMMATES_SET_OUTBOUND_LIVE_/, 'Teammates set outbound live — ')
    .replace(/^COUNT_TEAMMATES_/, 'Teammates — ')
    .replace(/^COUNT_ADMINS_/, 'Teammates — ')
    .replace(/^COUNT_USERS_VIEWED_ARTICLE_/, 'Users viewed article — ')
    .replace(/^COUNT_USERS_SEARCHED_ARTICLE_/, 'Users searched article — ')
    .replace(/^COUNT_ARTICLES_VIEWED_/, 'Articles viewed — ')
    .replace(/^COUNT_ARTICLE_VIEWS_/, 'Article views — ')
    .replace(/^COUNT_ARTICLE_SEARCHES_/, 'Article searches — ')
    .replace(/^COUNT_TICKETS_CREATED_VIA_/, 'Tickets created via — ')
    .replace(/^COUNT_TICKETS_CATEGORY_/, 'Tickets — ')
    .replace(/^COUNT_TICKETS_/, 'Tickets — ')
    .replace(/^COUNT_FIN_INVOLVED_ADDRESSABLE_CONVERSATIONS_WITH_PROCEDURES_/, 'Fin procedures (addressable) — ')
    .replace(/^COUNT_FIN_INVOLVED_CONVERSATIONS_WITH_PROCEDURES_/, 'Fin procedures — ')
    .replace(/^COUNT_FIN_AI_AGENT_/, 'Fin AI agent — ')
    .replace(/^TOTAL_FIN_AI_AGENT_/, 'Fin AI agent (total) — ')
    .replace(/^COUNT_SALES_AGENT_/, 'Sales agent — ')
    .replace(/^SALES_AGENT_/, 'Sales agent — ')
    .replace(/^COUNT_PHONE_CALLS_/, 'Phone calls — ')
    .replace(/^COUNT_CALLS_/, 'Calls — ')
    .replace(/^COUNT_MESSENGER_CALLS_/, 'Messenger calls — ')
    .replace(/^COUNT_OUTBOUND_END_USERS_/, 'Outbound end users — ')
    .replace(/^COUNT_END_USERS_/, 'End users — ')
    .replace(/^COUNT_VISITS_/, 'Visits — ')
    .replace(/^COUNT_VIEWS_/, 'Views — ')
    .replace(/^COUNT_CLICKS_/, 'Clicks — ')
    .replace(/^COUNT_/, '')
    .replace(/^TOTAL_/, '')
    .replace(/_CONTENT_TYPE/g, '')
    .replace(/_INITIAL_CHANNEL/g, ' (initial channel)')
    .replace(/_RATE$/, ' rate')
    .replace(/_/g, ' ')
    .toLowerCase()
    .replace(/(?:^|\s)\S/g, c => c.toUpperCase())
    .replace(/\bFin\b/g, 'Fin')
    .replace(/\bCsat\b/g, 'CSAT')
    .replace(/\bAi\b/g, 'AI')
    .replace(/\bSms\b/g, 'SMS')
    .replace(/\bSla\b/g, 'SLA')
    .replace(/\bApi\b/g, 'API')
    .replace(/\bCx\b/g, 'CX')
    .replace(/\bLlm\b/g, 'LLM')
    .replace(/\bOsa\b/g, 'OSA')
    .replace(/\bCsv\b/g, 'CSV');
  return s;
}

// ─── Auto-group assignment ────────────────────────────────────────────────────
function autoGroup(col) {
  if (col === 'POSITIVE_CUSTOMER_EXPERIENCE_SCORES_RATE' || /CX_SCORE/.test(col)) return 'CX Score';
  if (/SUGGESTIONS_|ACCEPTED_SUGGESTIONS|COPILOT/.test(col)) return 'Copilot / Suggestions';
  if (/SALES_AGENT|CONTACT_CAPTURES|ABANDONED_CONVERSATIONS|DISQUALIFIED|PRODUCT_DISCOVERY|UNCHARGEABLE/.test(col)) return 'Sales Agent';
  if (/TOPICS_|TOPIC_TRENDS/.test(col)) return 'Topics & AI Insights';
  if (/AI_INSIGHTS_QUERY_TYPE/.test(col)) return 'Topics & AI Insights';
  if (/COUNT_LIVE_FIN_TASKS|COUNT_FIRST_SET_LIVE_FIN_TASKS|COUNT_NEW_FIN_TASKS|COUNT_DRAFT_FIN_TASKS|COUNT_PAUSED_FIN_TASKS|COUNT_ANSWERS_LIVE|WITH_FIN_GUIDANCE|_ATTRIBUTE$|VISITS_FIN_|VISITED_FIN_|VISITS_CUSTOM_ANSWERS|VISITED_CUSTOM_ANSWERS/.test(col)) return 'Fin Setup & Configuration';
  if (/WITH_PROCEDURES|PROCEDURES_CONFIGURED|PROCEDURES_STARTED|PROCEDURES_FINISHED/.test(col)) return 'Fin Procedures';
  if (/FIN_VOICE|INBOUND_PHONE_CONVERSATIONS_WITH_FIN/.test(col)) return 'Phone / Fin Voice';
  if (/^COUNT_PHONE|^COUNT_INBOUND_PHONE|^COUNT_CALLS|^COUNT_MESSENGER_CALL|^TOTAL_CALL|WITH_CALL|WITH_INBOUND_CALL|WITH_OUTBOUND_CALL|PHONE_SETTING/.test(col)) return 'Phone / Calls';
  if (/FIN_ELIGIBLE|FIN_ADDRESSABLE|FIN_SENT|HARD_RESOLVED|SOFT_RESOLVED|RESOLUTION_BOT|FIN_AI_AGENT|TOTAL_FIN_AI_AGENT|FIN_TASKS|FIN_SETUP|FIN_CONTENT|FIN_SETTINGS|MANAGE_FIN|VISITS_FIN|VISITED_FIN|INTERACTING_WITH_FIN/.test(col)) return 'Fin AI';
  if (/FIN_GUIDANCE|FIN_INVOLVED/.test(col)) return 'Fin AI';
  if (/WHATSAPP|INSTAGRAM|FACEBOOK|TWITTER|SMS_CONTENT/.test(col)) return 'Channels — Messaging';
  if (/_CHAT_CONTENT|_EMAIL_CONTENT|_MESSENGER_CONTENT|_POST_CONTENT|_PUSH_ONLY/.test(col)) return 'Channels — Core';
  if (/WITH_WORKFLOW|COMPLETED_WORKFLOW|NEW_WORKFLOW|DRAFT_WORKFLOW|LIVE_WORKFLOW|PAUSED_WORKFLOW|WORKFLOW_TRIGGERS|WORKFLOW_TYPES|CUSTOM_BOT|FIN_TASK/.test(col)) return 'Workflows & Automation';
  if (/_RATING|RATED_|AI_CSAT|SERVICE_CONVERSATIONS/.test(col)) return 'CSAT / Ratings';
  if (/ARTICLE_|LIVE_ARTICLES|ARTICLES_VIEWED|USERS_VIEWED_ARTICLE|USERS_SEARCHED_ARTICLE|UNANSWERED_QUESTION|SUGGESTED_ANSWER/.test(col)) return 'Articles / Help Center';
  if (/^COUNT_OUTBOUND_|^COUNT_SERIES_|^COUNT_OUTBOUNDS_/.test(col)) return 'Outbound & Engagement';
  if (/TICKETS/.test(col)) return 'Tickets';
  if (/TEAMMATES_|ADMINS_/.test(col)) return 'Teammates';
  if (/MACRO_|MACROS/.test(col)) return 'Macros & Rules';
  if (/WITH_ATTRIBUTE|WITH_SLA|WITH_INBOX_RULE|WITH_BALANCED|WITH_ROUND_ROBIN|WITH_TAG|TOPIC_VERSIONS/.test(col)) return 'Automation Rules';
  if (/VISITS_|VIEWS_|CLICKS_|INTEGRATION|OSA2|CSV_REPORTS|SHARING/.test(col)) return 'In-App Engagement';
  return 'Inbox / Conversations';
}

// ─── Build METRICS, METRIC_LABELS, METRIC_GROUPS dynamically ─────────────────
const METRICS = {};
AMD_COLS.forEach(col => {
  METRICS[col] = { label: LABEL_OVERRIDES[col] || autoLabel(col), table: AMD };
});
MFR_ONLY_COLS.forEach(col => {
  METRICS[col] = { label: LABEL_OVERRIDES[col] || autoLabel(col), table: MFR };
});

// Flat key → label map for the GET endpoint
const METRIC_LABELS = Object.fromEntries(Object.entries(METRICS).map(([k, v]) => [k, v.label]));

// Grouped for the frontend searchable picker, sorted alphabetically within each group
const GROUP_ORDER = [
  'Inbox / Conversations', 'Fin AI', 'Fin Setup & Configuration', 'Fin Procedures', 'CSAT / Ratings', 'CX Score',
  'Channels — Core', 'Channels — Messaging', 'Topics & AI Insights',
  'Workflows & Automation', 'Articles / Help Center', 'Outbound & Engagement',
  'Phone / Calls', 'Phone / Fin Voice', 'Copilot / Suggestions',
  'Sales Agent', 'Tickets', 'Teammates', 'Macros & Rules', 'Automation Rules', 'In-App Engagement',
];
const _groupMap = {};
Object.keys(METRICS).forEach(key => {
  const g = autoGroup(key);
  if (!_groupMap[g]) _groupMap[g] = [];
  _groupMap[g].push(key);
});
const METRIC_GROUPS = GROUP_ORDER
  .filter(g => _groupMap[g]?.length)
  .map(g => ({
    label: g,
    keys: _groupMap[g].sort((a, b) => METRICS[a].label.localeCompare(METRICS[b].label)),
  }));

// ─── Product Actions (workspace-level admin activation tracking) ──────────────
// Key prefix 'ACTION:' distinguishes these from daily-aggregate METRICS.
// Instead of comparing avg metric values, the tool measures:
//   % of workspaces that PERFORMED this admin action in 30 days post-campaign
//   vs a control group of non-recipient paid workspaces.
const PRODUCT_ACTIONS = {
  'ACTION:FIN_GUIDANCE_CREATED': {
    label: 'Fin guidance — workspace created new guidance ↗',
    table: 'CORE_PRODUCT.FCT_CONVERSATION_APPLIED_FIN_GUIDANCE',
    dateCol: 'FIN_GUIDANCE_CREATED_AT',
    note: 'Only counts guidance that was eventually applied to at least one Fin conversation.',
  },
  'ACTION:FIN_GUIDANCE_LIVE': {
    label: 'Fin guidance — workspace has live guidance active ↗',
    table: 'CORE_PRODUCT.FCT_CONVERSATION_APPLIED_FIN_GUIDANCE',
    dateCol: 'FIN_GUIDANCE_CREATED_AT',
    filter: "FIN_GUIDANCE_STATE_NAME = 'live'",
    note: 'Workspace created guidance (currently live) in the 30-day post-campaign window.',
  },
  'ACTION:FIN_PROCEDURE_CREATED': {
    label: 'Fin procedures — workspace created a new procedure ↗',
    table: 'CORE_PRODUCT.DIM_PROCEDURES',
    dateCol: 'PROCEDURE_CREATED_AT',
  },
  'ACTION:FIN_PROCEDURE_SET_LIVE': {
    label: 'Fin procedures — workspace first set a procedure live ↗',
    table: 'CORE_PRODUCT.DIM_PROCEDURES',
    dateCol: 'PROCEDURE_FIRST_SET_LIVE_AT',
    note: 'Tracks the first time each procedure was set live. Repeat publishes not counted.',
  },
  // Fin Tasks (from DIM_WORKFLOW_INSTANCES)
  'ACTION:FIN_TASK_CREATED': {
    label: 'Fin tasks — workspace created a new Fin task ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'INSTANCE_CREATED_AT',
    filter: 'IS_FIN_TASK = TRUE',
  },
  'ACTION:FIN_TASK_SET_LIVE': {
    label: 'Fin tasks — workspace first set a Fin task live ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'WORKFLOW_FIRST_SET_LIVE_AT',
    filter: 'IS_FIN_TASK = TRUE',
  },
  'ACTION:FIN_TASK_SOPHISTICATED_TEST': {
    label: 'Fin tasks — workspace first ran a sophisticated test ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'SOPHISTICATED_TEST_FIRST_RUN_AT',
    filter: 'IS_FIN_TASK = TRUE',
    note: 'Sophisticated testing = workspace tested their Fin task before going live.',
  },
  // Workflows with Fin (from DIM_WORKFLOW_INSTANCES)
  'ACTION:WORKFLOW_WITH_FIN_SET_LIVE': {
    label: 'Workflows — workspace set live a workflow containing a Fin step ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'WORKFLOW_FIRST_SET_LIVE_AT',
    filter: 'HAD_FIN_ANSWER_STEP_EVER = TRUE AND IS_FIN_TASK = FALSE AND IS_PROCEDURE = FALSE',
    note: 'Standard workflows (not Fin Tasks or Procedures) that include a Fin answer step.',
  },
  'ACTION:WORKFLOW_DATA_CONNECTOR_ADDED': {
    label: 'Workflows — workspace added a data connector step ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'DATA_CONNECTOR_STEP_FIRST_ADDED_AT',
    note: 'Tracks when a workspace first added an API/data connector step to any workflow.',
  },
  // Fin trial (from FCT_FIN_TRIALS)
  'ACTION:FIN_TRIAL_STARTED': {
    label: 'Fin trial — workspace started their first Fin trial ↗',
    table: 'CORE_PRODUCT.FCT_FIN_TRIALS',
    dateCol: 'START_DATE',
    filter: 'IS_FIRST_TRIAL = TRUE',
    note: 'Only counts the first-ever Fin trial per workspace.',
  },
  // Fin first conversation (from FCT_APPS_CMF_RETURNS — app-level activation)
  'ACTION:FIN_FIRST_CONVERSATION': {
    label: 'Fin activation — workspace had their very first Fin conversation ↗',
    table: 'CORE_PRODUCT.FCT_APPS_CMF_RETURNS',
    dateCol: 'CALENDAR_DATE_FIRST_FIN_OR_LEGACY_RESOLUTION_BOT_CONVERSATION',
    note: 'Counts workspaces whose first-ever Fin (or legacy Resolution Bot) conversation happened in the 30-day post-campaign window. Strong activation signal.',
  },
  // Workflow actions — additional signals from DIM_WORKFLOW_INSTANCES
  'ACTION:WORKFLOW_FIN_INSTRUCTIONS_ADDED': {
    label: 'Workflows — workspace added a Fin Instructions step ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'FIN_INSTRUCTIONS_STEP_FIRST_ADDED_AT',
    note: 'Tracks when a workspace first added a Fin Instructions (knowledge source) step to any workflow.',
  },
  'ACTION:FIN_PROCEDURE_AI_GENERATED': {
    label: 'Fin procedures — workspace created an AI-generated procedure ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'INSTANCE_CREATED_AT',
    filter: 'IS_AI_GENERATED_PROCEDURE = TRUE',
    note: 'AI-generated procedures are created by Fin automatically from existing content.',
  },
  'ACTION:WORKFLOW_CREATED': {
    label: 'Workflows — workspace created any new workflow ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'INSTANCE_CREATED_AT',
    filter: 'IS_FIN_TASK = FALSE AND IS_PROCEDURE = FALSE',
    note: 'Standard workflows (not Fin Tasks or Procedures). Broad signal for workflow builder engagement.',
  },
  'ACTION:WORKFLOW_SET_LIVE': {
    label: 'Workflows — workspace set any workflow live ↗',
    table: 'CORE_PRODUCT.DIM_WORKFLOW_INSTANCES',
    dateCol: 'WORKFLOW_FIRST_SET_LIVE_AT',
    filter: 'IS_FIN_TASK = FALSE AND IS_PROCEDURE = FALSE',
    note: 'Standard workflows (not Fin Tasks or Procedures) first set live. Broader activation signal than Fin-specific workflows.',
  },
};

function generateJWT() {
  const pk = (process.env.SNOWFLAKE_PRIVATE_KEY || '').replace(/\\n/g, '\n');
  if (!pk) throw new Error('SNOWFLAKE_PRIVATE_KEY not configured');

  const account = (process.env.SNOWFLAKE_ACCOUNT || 'PEOSZPH-INTERCOM_US').toUpperCase();
  const user = (process.env.SNOWFLAKE_USER || 'SHANE_RYAN').toUpperCase();

  const privateKey = crypto.createPrivateKey(pk);
  const publicKey = crypto.createPublicKey(privateKey);
  const pubDer = publicKey.export({ type: 'spki', format: 'der' });
  const fp = crypto.createHash('sha256').update(pubDer).digest('base64');

  const now = Math.floor(Date.now() / 1000);
  const header = Buffer.from(JSON.stringify({ alg: 'RS256', typ: 'JWT' })).toString('base64url');
  const payload = Buffer.from(JSON.stringify({
    iss: `${account}.${user}.SHA256:${fp}`,
    sub: `${account}.${user}`,
    iat: now,
    exp: now + 3600,
  })).toString('base64url');

  const sign = crypto.createSign('SHA256');
  sign.update(`${header}.${payload}`);
  const sig = sign.sign(privateKey, 'base64url');
  return `${header}.${payload}.${sig}`;
}

async function runQuery(sql, jwt) {
  const account = (process.env.SNOWFLAKE_ACCOUNT || 'PEOSZPH-INTERCOM_US').toLowerCase();
  const url = `https://${account}.snowflakecomputing.com/api/v2/statements`;

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${jwt}`,
      'X-Snowflake-Authorization-Token-Type': 'KEYPAIR_JWT',
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    },
    body: JSON.stringify({
      statement: sql,
      warehouse: process.env.SNOWFLAKE_WAREHOUSE || 'WH_INTERCOMRADE',
      database: 'INTERCOM_PROD',
      timeout: 50,
    }),
  });

  const body = await res.json();

  // Already complete
  if (body.resultSetMetaData) return parseRows(body);

  // Failed immediately
  if (!res.ok) throw new Error(body.message || `Snowflake error ${res.status}`);

  // Async — poll
  if (body.statementHandle) return poll(body.statementHandle, jwt, account);

  throw new Error('Unexpected Snowflake response');
}

async function poll(handle, jwt, account) {
  const url = `https://${account}.snowflakecomputing.com/api/v2/statements/${handle}`;
  for (let i = 0; i < 25; i++) {
    await new Promise(r => setTimeout(r, 2000));
    const res = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${jwt}`,
        'X-Snowflake-Authorization-Token-Type': 'KEYPAIR_JWT',
        'Accept': 'application/json',
      },
    });
    const body = await res.json();
    if (body.status === 'failed') throw new Error(body.message || 'Query failed');
    if (body.resultSetMetaData) return parseRows(body);
  }
  throw new Error('Query timed out after 50 seconds');
}

function parseRows(body) {
  if (!body.resultSetMetaData || !body.data) return [];
  const cols = body.resultSetMetaData.rowType.map(c => c.name);
  return body.data.map(row => {
    const obj = {};
    cols.forEach((c, i) => { obj[c] = row[i]; });
    return obj;
  });
}

module.exports = async function (req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');

  // Return available metrics + product actions list
  if (req.method === 'GET') {
    const actionLabels = Object.fromEntries(Object.entries(PRODUCT_ACTIONS).map(([k, v]) => [k, v.label]));
    const actionGroup  = { label: 'Product Actions (Admin)', keys: Object.keys(PRODUCT_ACTIONS) };
    return res.status(200).json({
      metrics: { ...METRIC_LABELS, ...actionLabels },
      groups:  [...METRIC_GROUPS, actionGroup],
    });
  }

  if (req.method !== 'POST') return res.status(405).end();

  const { rulesetId, featureMetric } = req.body || {};

  if (!rulesetId || isNaN(Number(rulesetId))) {
    return res.status(400).json({ error: 'Invalid rulesetId — must be a number.' });
  }
  if (!featureMetric || (!METRICS[featureMetric] && !PRODUCT_ACTIONS[featureMetric])) {
    return res.status(400).json({ error: 'Invalid featureMetric.' });
  }

  const pk = process.env.SNOWFLAKE_PRIVATE_KEY;
  if (!pk) {
    return res.status(503).json({
      setupRequired: true,
      error: 'Snowflake credentials not yet configured. Add SNOWFLAKE_PRIVATE_KEY to Vercel environment variables. See the setup guide below.',
    });
  }

  try {
    const jwt = generateJWT();
    const rid = Number(rulesetId);
    const metric = featureMetric; // already validated against whitelist

    // ── Query 1: campaign metadata (fast) ────────────────────────────────
    const metaSQL = `
      SELECT
        DATE(MIN(CREATED_AT))::TEXT                                                 AS SEND_DATE,
        COUNT(DISTINCT USER_ID)                                                     AS TOTAL_RECIPIENTS,
        ROUND(AVG(CASE WHEN OPEN_ID IS NOT NULL THEN 1.0 ELSE 0.0 END) * 100, 1)   AS OPEN_RATE,
        ROUND(AVG(CASE WHEN WAS_CLICKED THEN 1.0 ELSE 0.0 END) * 100, 1)           AS CLICK_RATE
      FROM INTERCOM_PROD.CORE_PRODUCT.FCT_OUTBOUND_RECEIPTS
      WHERE APP_ID = 6
        AND RULESET_ID = ${rid}
        AND CONTENT_TYPE = 'email'
    `;

    const metaRows = await runQuery(metaSQL, jwt);
    const meta = metaRows[0] || {};

    if (!meta.SEND_DATE || meta.TOTAL_RECIPIENTS === '0') {
      return res.status(404).json({
        error: `No email receipts found for RULESET_ID ${rid}. Check the ID is correct — find it in the Intercom series URL (…/outbound/series/XXXXXXXX).`,
      });
    }

    // ── Product Action path: workspace activation rate ─────────────────────
    if (PRODUCT_ACTIONS[featureMetric]) {
      const action = PRODUCT_ACTIONS[featureMetric];
      const filterClause = action.filter ? `AND a.${action.filter}` : '';

      const actionSQL = `
WITH send_info AS (
  SELECT DATE(MIN(CREATED_AT)) AS sd
  FROM INTERCOM_PROD.CORE_PRODUCT.FCT_OUTBOUND_RECEIPTS
  WHERE APP_ID = 6 AND RULESET_ID = ${rid} AND CONTENT_TYPE = 'email'
),
recipients AS (
  SELECT DISTINCT t.DEFAULT_APP_ID AS app_id
  FROM INTERCOM_PROD.CORE_PRODUCT.FCT_OUTBOUND_RECEIPTS r
  JOIN INTERCOM_PROD.CORE_PRODUCT.DIM_TEAMMATES t ON r.USER_ID = t.I4I_USER_ID
  WHERE r.APP_ID = 6
    AND r.RULESET_ID = ${rid}
    AND r.CONTENT_TYPE = 'email'
    AND t.DEFAULT_APP_ID IS NOT NULL
  LIMIT 2000
),
control_group AS (
  SELECT a.APP_ID AS app_id
  FROM INTERCOM_PROD.CORE_COMMON.DIM_APPS a
  LEFT JOIN recipients r ON a.APP_ID = r.app_id
  WHERE a.IS_PAID_APP_NOW = true
    AND a.IS_DELETED_APP = false
    AND a.INCLUDE_IN_ANALYSIS = true
    AND r.app_id IS NULL
  LIMIT 2000
),
cohorts AS (
  SELECT app_id, 'recipient' AS cohort FROM recipients
  UNION ALL
  SELECT app_id, 'control'   AS cohort FROM control_group
),
action_after AS (
  SELECT DISTINCT a.APP_ID AS app_id
  FROM INTERCOM_PROD.${action.table} a
  CROSS JOIN send_info s
  WHERE a.${action.dateCol} > s.sd
    AND a.${action.dateCol} <= DATEADD('day', 30, s.sd)
    ${filterClause}
),
action_before AS (
  SELECT DISTINCT a.APP_ID AS app_id
  FROM INTERCOM_PROD.${action.table} a
  CROSS JOIN send_info s
  WHERE a.${action.dateCol} >= DATEADD('day', -30, s.sd)
    AND a.${action.dateCol} < s.sd
    ${filterClause}
),
summary AS (
  SELECT
    'S'                                                                         AS tp,
    c.cohort,
    COUNT(DISTINCT c.app_id)                                                    AS total_ws,
    COUNT(DISTINCT CASE WHEN aa.app_id IS NOT NULL THEN c.app_id END)           AS activated_after,
    COUNT(DISTINCT CASE WHEN ab.app_id IS NOT NULL THEN c.app_id END)           AS activated_before
  FROM cohorts c
  LEFT JOIN action_after  aa ON c.app_id = aa.app_id
  LEFT JOIN action_before ab ON c.app_id = ab.app_id
  GROUP BY c.cohort
),
daily_actions AS (
  SELECT
    'T'                                                                         AS tp,
    c.cohort,
    DATE(a.${action.dateCol})::TEXT                                              AS dt,
    COUNT(DISTINCT c.app_id)                                                    AS cnt
  FROM INTERCOM_PROD.${action.table} a
  JOIN cohorts c ON a.APP_ID = c.app_id
  CROSS JOIN send_info s
  WHERE a.${action.dateCol} > s.sd
    AND a.${action.dateCol} <= DATEADD('day', 30, s.sd)
    ${filterClause}
  GROUP BY c.cohort, DATE(a.${action.dateCol})
)
SELECT tp, cohort, total_ws::TEXT, activated_after::TEXT, activated_before::TEXT, NULL::TEXT AS dt, NULL::TEXT AS cnt
FROM summary
UNION ALL
SELECT tp, cohort, NULL::TEXT, NULL::TEXT, NULL::TEXT, dt, cnt::TEXT
FROM daily_actions
ORDER BY tp DESC, cohort, dt
      `;

      const actionRows = await runQuery(actionSQL, jwt);
      const sumRows = actionRows.filter(r => r.TP === 'S');
      const dayRows = actionRows.filter(r => r.TP === 'T');

      const buildCohort = (cohort) => {
        const row    = sumRows.find(r => r.COHORT === cohort) || {};
        const total  = Number(row.TOTAL_WS || 0);
        const after  = Number(row.ACTIVATED_AFTER  || 0);
        const before = Number(row.ACTIVATED_BEFORE || 0);
        return {
          cohort,
          totalWorkspaces:      total,
          activatedAfter:       after,
          activatedBefore:      before,
          activationRateAfter:  total > 0 ? Math.round(after  / total * 1000) / 10 : 0,
          activationRateBefore: total > 0 ? Math.round(before / total * 1000) / 10 : 0,
        };
      };

      const recipient = buildCohort('recipient');
      const control   = buildCohort('control');

      const dates = [...new Set(dayRows.map(r => r.DT))].sort();
      const timeline = dates.map(date => {
        const rRow = dayRows.find(r => r.COHORT === 'recipient' && r.DT === date);
        const cRow = dayRows.find(r => r.COHORT === 'control'   && r.DT === date);
        return {
          date,
          recipientPct: recipient.totalWorkspaces > 0
            ? Math.round(Number(rRow?.CNT || 0) / recipient.totalWorkspaces * 1000) / 10 : 0,
          controlPct: control.totalWorkspaces > 0
            ? Math.round(Number(cRow?.CNT || 0) / control.totalWorkspaces * 1000) / 10 : 0,
        };
      });

      return res.status(200).json({
        campaign: {
          rulesetId:         rid,
          sendDate:          meta.SEND_DATE,
          totalRecipients:   Number(meta.TOTAL_RECIPIENTS),
          matchedWorkspaces: recipient.totalWorkspaces,
          matchRate: meta.TOTAL_RECIPIENTS > 0
            ? Math.round(recipient.totalWorkspaces / Number(meta.TOTAL_RECIPIENTS) * 100) : 0,
          openRate:  Number(meta.OPEN_RATE),
          clickRate: Number(meta.CLICK_RATE),
        },
        actionMode:   true,
        featureMetric,
        featureLabel: action.label,
        actionNote:   action.note || null,
        recipient,
        control,
        lift: Math.round((recipient.activationRateAfter - control.activationRateAfter) * 10) / 10,
        timeline,
      });
    }

    // ── Query 2: combined analysis + timeline ─────────────────────────────
    // Returns rows with TYPE = 'S' (summary) or 'T' (timeline)
    const analysisSQL = `
WITH send_info AS (
  SELECT DATE(MIN(CREATED_AT)) AS sd
  FROM INTERCOM_PROD.CORE_PRODUCT.FCT_OUTBOUND_RECEIPTS
  WHERE APP_ID = 6 AND RULESET_ID = ${rid} AND CONTENT_TYPE = 'email'
),
recipients AS (
  SELECT DISTINCT t.DEFAULT_APP_ID AS app_id
  FROM INTERCOM_PROD.CORE_PRODUCT.FCT_OUTBOUND_RECEIPTS r
  JOIN INTERCOM_PROD.CORE_PRODUCT.DIM_TEAMMATES t ON r.USER_ID = t.I4I_USER_ID
  WHERE r.APP_ID = 6
    AND r.RULESET_ID = ${rid}
    AND r.CONTENT_TYPE = 'email'
    AND t.DEFAULT_APP_ID IS NOT NULL
  LIMIT 2000
),
control_group AS (
  SELECT a.APP_ID AS app_id
  FROM INTERCOM_PROD.CORE_COMMON.DIM_APPS a
  LEFT JOIN recipients r ON a.APP_ID = r.app_id
  WHERE a.IS_PAID_APP_NOW = true
    AND a.IS_DELETED_APP = false
    AND a.INCLUDE_IN_ANALYSIS = true
    AND r.app_id IS NULL
  LIMIT 2000
),
cohorts AS (
  SELECT app_id, 'recipient' AS cohort FROM recipients
  UNION ALL
  SELECT app_id, 'control'   AS cohort FROM control_group
),
feature_data AS (
  SELECT
    c.cohort,
    f.APP_ID,
    f.CALENDAR_DATE,
    COALESCE(f.${metric}, 0) AS val
  FROM cohorts c
  JOIN INTERCOM_PROD.CORE_PRODUCT.${METRICS[metric].table} f ON c.app_id = f.APP_ID
  CROSS JOIN send_info s
  WHERE f.CALENDAR_DATE BETWEEN DATEADD('day', -30, s.sd)
                             AND DATEADD('day',  30, s.sd)
),
summary AS (
  SELECT
    'S'                                                                                     AS tp,
    cohort,
    CASE WHEN CALENDAR_DATE < (SELECT sd FROM send_info) THEN 'before' ELSE 'after' END    AS period,
    COUNT(DISTINCT APP_ID)                                                                  AS n,
    ROUND(SUM(val) / NULLIF(COUNT(DISTINCT APP_ID), 0), 4)                                 AS avg_val,
    ROUND(COUNT(DISTINCT CASE WHEN val > 0 THEN APP_ID END) * 100.0
          / NULLIF(COUNT(DISTINCT APP_ID), 0), 1)                                           AS pct_active
  FROM feature_data
  GROUP BY cohort, CASE WHEN CALENDAR_DATE < (SELECT sd FROM send_info) THEN 'before' ELSE 'after' END
),
timeline AS (
  SELECT
    'T'                                                                                     AS tp,
    CALENDAR_DATE::TEXT                                                                     AS cohort,
    'n/a'                                                                                   AS period,
    NULL::NUMBER                                                                            AS n,
    ROUND(SUM(CASE WHEN cohort = 'recipient' THEN val ELSE 0 END)
          / NULLIF(COUNT(DISTINCT CASE WHEN cohort = 'recipient' THEN APP_ID END), 0), 4)  AS avg_val,
    ROUND(SUM(CASE WHEN cohort = 'control' THEN val ELSE 0 END)
          / NULLIF(COUNT(DISTINCT CASE WHEN cohort = 'control' THEN APP_ID END), 0), 4)    AS pct_active
  FROM feature_data
  GROUP BY CALENDAR_DATE
)
SELECT tp, cohort, period, n::TEXT, avg_val::TEXT, pct_active::TEXT
FROM summary
UNION ALL
SELECT tp, cohort, period, n::TEXT, avg_val::TEXT, pct_active::TEXT
FROM timeline
ORDER BY tp DESC, cohort, period
    `;

    const rows = await runQuery(analysisSQL, jwt);

    const summary = rows
      .filter(r => r.TP === 'S')
      .map(r => ({
        cohort: r.COHORT,
        period: r.PERIOD,
        appCount: Number(r.N || 0),
        avgPerApp: Number(r.AVG_VAL || 0),
        pctActive: Number(r.PCT_ACTIVE || 0),
      }));

    const timeline = rows
      .filter(r => r.TP === 'T')
      .map(r => ({
        date: r.COHORT,
        recipientAvg: Number(r.AVG_VAL || 0),
        controlAvg: Number(r.PCT_ACTIVE || 0),
      }))
      .sort((a, b) => a.date.localeCompare(b.date));

    const recipientCount = summary.find(r => r.cohort === 'recipient')?.appCount || 0;

    return res.status(200).json({
      campaign: {
        rulesetId: rid,
        sendDate: meta.SEND_DATE,
        totalRecipients: Number(meta.TOTAL_RECIPIENTS),
        matchedWorkspaces: recipientCount,
        matchRate: meta.TOTAL_RECIPIENTS > 0
          ? Math.round((recipientCount / Number(meta.TOTAL_RECIPIENTS)) * 100)
          : 0,
        openRate: Number(meta.OPEN_RATE),
        clickRate: Number(meta.CLICK_RATE),
      },
      summary,
      timeline,
      featureMetric,
      featureLabel: METRICS[featureMetric].label,
    });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};
